### ISSUE TITLE
Template: unwanted gap

### ISSUE THREAD

**Issue by cjmaxik** [FlyingSixtySix/neuro-scheduler#3]
There is a 1px wide gap present between the Sunday's slot and the edge of Evil's base image.

![image](https://github.com/VanillaSixtySix/neuro-scheduler/assets/1501705/32831d52-0957-4175-b3b2-55f0df31db2a)

Literally unusable.
Please fix asap.

**Comment by VanillaSixtySix** [comment]
suffering
